/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "CorrectaSite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "CsrfSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ExamAssets": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "InstitutionCookieSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MigrateDb": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MinioAccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MinioSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NextauthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenaiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}